### ISSUE TITLE
Merge expected content types and output stream names into a single start signal attribute

### ISSUE THREAD

**Issue by fbiville** [projectriff/invoker-specification#8]
That way, there cannot be any inconsistency between the two, and invokers won't have to check it.

**Comment by ericbottard** [comment]
IMO it's better to have two lists than a map (unordered and a PITA to handle with protobuf) or a list with custom elements that need to be parsed.
I'd rather disregard this issue. Whether invokers want to double checks that the two lists have the same size is up to them, but this should be deemed true by design.

**Comment by scothis** [comment]
Note: I'm using protocol buffers terminology here and not riff terms, since there is a namespace clash.

Unless there is a significant performance penalty, I lean towards the proto being a single repeated message instead of multiple repeated fields that must be accessed with a coordinated index. Logically it makes more sense and make the protocol more flexible as we want to add new fields to the message, particularly for values that may be optional.

**Comment by ericbottard** [comment]
Could you clarify "message" vs "fields" in your comment?

Are you saying
```
// Contains setup data for an invocation
message StartFrame {
    // The ContentTypes that an invocation is allowed to produce for each output parameter
    repeated OuputMetadata outputs = 1;
    // The logical names for input arguments
    repeated string inputNames = 2; // Could be adapted as well, irrelevant here
}

message OutputMetadata {
    string name = 1;
    string expectedContentType = 2;
}
```
vs the current
```
// Contains setup data for an invocation
message StartFrame {
    // The ContentTypes that an invocation is allowed to produce for each output parameter
    repeated string expectedContentTypes = 1;
    // The logical names for input arguments
    repeated string inputNames = 2;
    // The logical names for output arguments
    repeated string outputNames = 3;
}
```
